let properties: Array<any> = [
    {
        id: 1,
        address: "1st NTMK",
        city: "HCM",
        state: "VN",
        zip: "084",
        title: "TOLBIAC - Ilôt T7 - Dalle de couverture des voies",
        zones: 4,
        levels: 3,
        posts: 2,
        long: -71.11095,
        lat: 42.35663,
        picture: "http://localhost:8100/assets/img/pict1.jpg",
        thumbnail: "http://localhost:8100/assets/img/pict1.jpg",
        tags: "site",
        description: "Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet",
        manager: {
            id: 1,
            name: "John Doe",
            title: "Supervisor",
            picture: "http://localhost:8100/assets/img/avatar.png"
        }
    },
    {
        id: 2,
        address: "1st NTMK",
        city: "HCM",
        state: "VN",
        zip: "084",
        title: "TOLBIAC - Ilôt T7 - Dalle de couverture des voies",
        zones: 4,
        levels: 3,
        posts: 2,
        long: -71.11095,
        lat: 42.35663,
        picture: "http://localhost:8100/assets/img/pict1.jpg",
        thumbnail: "http://localhost:8100/assets/img/pict1.jpg",
        tags: "site",
        description: "Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet",
        manager: {
            id: 1,
            name: "John Doe",
            title: "Supervisor",
            picture: "http://localhost:8100/assets/img/avatar.png"
        }
    },
    {
        id: 3,
        address: "2nd NTMK",
        city: "HCM",
        state: "VN",
        zip: "084",
        title: "PHARMASTER",
        zones: 4,
        levels: 3,
        posts: 2,
        long: -71.11095,
        lat: 42.35663,
        picture: "http://localhost:8100/assets/img/pict2.jpg",
        thumbnail: "http://localhost:8100/assets/img/pict2.jpg",
        tags: "site",
        description: "Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet",
        manager: {
            id: 1,
            name: "John Doe",
            title: "Supervisor",
            picture: "http://localhost:8100/assets/img/avatar.png"
        }
    },
    {
        id: 4,
        address: "3rd NTMK",
        city: "HCM",
        state: "VN",
        zip: "084",
        title: "Ehpad FOUG",
        zones: 4,
        levels: 3,
        posts: 2,
        long: -71.11095,
        lat: 42.35663,
        picture: "http://localhost:8100/assets/img/pict3.jpg",
        thumbnail: "http://localhost:8100/assets/img/pict3.jpg",
        tags: "site",
        description: "Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet",
        manager: {
            id: 1,
            name: "John Doe",
            title: "Supervisor",
            picture: "http://localhost:8100/assets/img/avatar.png"
        }
    },
    {
        id: 5,
        address: "4th NTMK",
        city: "HCM",
        state: "VN",
        zip: "084",
        title: "CREIL REHA MARTINIQUE",
        zones: 4,
        levels: 3,
        posts: 2,
        long: -71.11095,
        lat: 42.35663,
        picture: "http://localhost:8100/assets/img/pict4.jpg",
        thumbnail: "http://localhost:8100/assets/img/pict4.jpg",
        tags: "site",
        description: "Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet",
        manager: {
            id: 1,
            name: "John Doe",
            title: "Supervisor",
            picture: "http://localhost:8100/assets/img/avatar.png"
        }
    },
    {
        id: 6,
        address: "5th NTMK",
        city: "HCM",
        state: "VN",
        zip: "084",
        title: "Chantier Boufrit",
        zones: 4,
        levels: 3,
        posts: 2,
        long: -71.11095,
        lat: 42.35663,
        picture: "http://localhost:8100/assets/img/pict5.jpg",
        thumbnail: "http://localhost:8100/assets/img/pict5.jpg",
        tags: "site",
        description: "Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet",
        manager: {
            id: 1,
            name: "John Doe",
            title: "Supervisor",
            picture: "http://localhost:8100/assets/img/avatar.png"
        }
    },
    {
        id: 7,
        address: "6th NTMK",
        city: "HCM",
        state: "VN",
        zip: "084",
        title: "Chantier KOLA",
        zones: 4,
        levels: 3,
        posts: 2,
        long: -71.11095,
        lat: 42.35663,
        picture: "http://localhost:8100/assets/img/pict6.jpg",
        thumbnail: "http://localhost:8100/assets/img/pict6.jpg",
        tags: "site",
        description: "Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet",
        manager: {
            id: 1,
            name: "John Doe",
            title: "Supervisor",
            picture: "http://localhost:8100/assets/img/avatar.png"
        }
    },
    {
        id: 8,
        address: "1st NTMK",
        city: "HCM",
        state: "VN",
        zip: "084",
        title: "TOLBIAC - Ilôt T7 - Dalle de couverture des voies",
        zones: 4,
        levels: 3,
        posts: 2,
        long: -71.11095,
        lat: 42.35663,
        picture: "http://localhost:8100/assets/img/pict1.jpg",
        thumbnail: "http://localhost:8100/assets/img/pict1.jpg",
        tags: "site",
        description: "Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet",
        manager: {
            id: 1,
            name: "John Doe",
            title: "Supervisor",
            picture: "http://localhost:8100/assets/img/avatar.png"
        }
    },
    {
        id: 9,
        address: "1st NTMK",
        city: "HCM",
        state: "VN",
        zip: "084",
        title: "TOLBIAC - Ilôt T7 - Dalle de couverture des voies",
        zones: 4,
        levels: 3,
        posts: 2,
        long: -71.11095,
        lat: 42.35663,
        picture: "http://localhost:8100/assets/img/pict1.jpg",
        thumbnail: "http://localhost:8100/assets/img/pict1.jpg",
        tags: "site",
        description: "Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet",
        manager: {
            id: 1,
            name: "John Doe",
            title: "Supervisor",
            picture: "http://localhost:8100/assets/img/avatar.png"
        }
    },
    {
        id: 10,
        address: "1st NTMK",
        city: "HCM",
        state: "VN",
        zip: "084",
        title: "TOLBIAC - Ilôt T7 - Dalle de couverture des voies",
        zones: 4,
        levels: 3,
        posts: 2,
        long: -71.11095,
        lat: 42.35663,
        picture: "http://localhost:8100/assets/img/pict1.jpg",
        thumbnail: "http://localhost:8100/assets/img/pict1.jpg",
        tags: "site",
        description: "Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet",
        manager: {
            id: 1,
            name: "John Doe",
            title: "Supervisor",
            picture: "http://localhost:8100/assets/img/avatar.png"
        }
    },{
        id: 11,
        address: "1st NTMK",
        city: "HCM",
        state: "VN",
        zip: "084",
        title: "TOLBIAC - Ilôt T7 - Dalle de couverture des voies",
        zones: 4,
        levels: 3,
        posts: 2,
        long: -71.11095,
        lat: 42.35663,
        picture: "http://localhost:8100/assets/img/pict1.jpg",
        thumbnail: "http://localhost:8100/assets/img/pict1.jpg",
        tags: "site",
        description: "Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet...Lorem ipsum dolor sit amet",
        manager: {
            id: 1,
            name: "John Doe",
            title: "Supervisor",
            picture: "http://localhost:8100/assets/img/avatar.png"
        }
    }
];

export default properties;
